### ISSUE TITLE
Implement a data conversion pipeline (whatever -> JSON?).

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#11]
- [ ] check availability of data for the (two?) targeted patients,
- [ ] clinical data,
- [x] samples,
- [x] genetic variants,
- [ ] copy numbers,
- [ ] fusion genes,
- [ ] linked drugs.
- [ ] side-effects

**Comment by okunator** [comment]
Conversion of indication data to JSON in PR: #20

**Comment by jdreo** [comment]
Close this issue as too wide of a footprint, will open smaller, more atomic ones.
