### ISSUE TITLE
Cannot build frontend doc

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#18]
I failed to build the frontend's doc from within a fresh container.
The build ends on the following error:
```
Extension error (sphinx_js):
Handler <function analyze at 0x7fcb9e603310> for event 'builder-inited' threw an exception (exception: 'sources')
```
Steps:
- merge every current PR on main.
- `docker-compose build`
- `docker-compose run --rm nodeserver sh`
- `apk add py3-pip`
- `pip install sphinx sphinx-js trojanzoo_sphinx_theme`
- `cd docs/sphinx-js`
- `make html`

**Comment by jdreo** [comment]
Also tested with a local setup, and get the same error.

**Comment by jdreo** [comment]
I pushed the merged branches on [jdreo/develop](https://github.com/jdreo/oncodash/tree/develop) if one wants to check.

**Comment by prittt** [comment]
If u are using the sphinx-j module available on pip it's buggy. Please use the one in the requirements.txt file: [https://github.com/semohr/sphinx-js.git](https://github.com/semohr/sphinx-js.git)

**Comment by jdreo** [comment]
Works (locally) with sphinx-js at 07eb00c. Thanks.

**Comment by prittt** [comment]
Great!
