### ISSUE TITLE
Missing templates error

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#28]
# Bug description

Backend complains about missing templates.

# Steps to reproduce

1. Follow the docker-compose build and run steps.
2. Connect to `http://localhost:8888`

# Screenshots/logs

> Request Method: GET
> Request URL: http://localhost:8888/
> 
> Django Version: 3.2.12
> Python Version: 3.7.12
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'core',
>  'explainer',
>  'rest_framework',
>  'corsheaders']
> Installed Middleware:
> ['django.middleware.security.SecurityMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'corsheaders.middleware.CorsMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware']
> 
> Template loader postmortem
> Django tried loading these templates, in this order:
> 
> Using engine django:
>     * django.template.loaders.filesystem.Loader: /opt/oncodash-app/index.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/django/contrib/admin/templates/index.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/django/contrib/auth/templates/index.html (Source does not exist)
>     * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.7/site-packages/rest_framework/templates/index.html (Source does not exist)
> 
> 
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
>     response = response.render()
>   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 105, in render
>     self.content = self.rendered_content
>   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
>     template = self.resolve_template(self.template_name)
>   File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
>     return select_template(template, using=self.using)
>   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 47, in select_template
>     raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
> 
> Exception Type: TemplateDoesNotExist at /
> Exception Value: index.html

# Environment

 - Oncodash Version: 314e0db
 - OS: Ubuntu
 - Browser: Firefox 96.0

For developers:
 - Docker version: 20.10.12, build e91ed57
 - Docker-compose: 2.0.1

**Comment by okunator** [comment]
Try just `http://localhost/`. The `http://localhost:8888` points to a dev-server located inside the`backend`-container that does not contain the front-end side files.

**Comment by jdreo** [comment]
There's no process serving on port 80 and the only process that is shown is docker-proxy on port 8888.
However, I can see transient appearance of a process running on port 80, but that disappears rapidly.
The only running container returned by `docker ps -a` is the `backend_backend` one.

**Comment by okunator** [comment]
The nginx-container automatically restarts if it does not find  backend/frontend servers which can explain the transient processes on port 80... I can't reproduce the error locally so I'm not sure where this can be coming from. I need to investigate a bit more.

**Comment by jdreo** [comment]
Found the problem: the frontend server would not start because of a problem between docker and some kernel module. An update and reboot solved the issue.
