### ISSUE TITLE
New TSC errors when running version 6958782 (after PR #47)

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#48]
# Summary

New TSC errors when running version 6958782 (after PR #47).

# Bug full description

    > oncodash-app@0.0.0 start
    > tsc && concurrently -k -r "tsc --watch --preserveWatchOutput" "wds"

    src/explainer/explainer.ts(310,16): error TS2569: Type 'IterableIterator<Link>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/explainer/explainer.ts(311,16): error TS2569: Type 'IterableIterator<Link>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/explainer/explainer.ts(315,16): error TS2569: Type 'IterableIterator<Node>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/explainer/explainer.ts(316,16): error TS2569: Type 'IterableIterator<Node>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/explainer/explainer.ts(325,55): error TS2569: Type 'IterableIterator<Node>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/explainer/explainer.ts(326,51): error TS2569: Type 'IterableIterator<Link>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
    src/utils/tooltip.ts(53,9): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
    src/utils/tooltip.ts(60,9): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
    src/utils/tooltip.ts(64,9): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
    tsconfig.json(3,15): error TS6046: Argument for '--target' option must be: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'esnext'.

# Steps to reproduce

1. source backendEnv/bin/activate
2. python manage.py runserver 8888
3. npm start

# Environment

 - Oncodash Version: 6958782
 - OS: Ubuntu focal 20.04 LTS

For developers:
 - Python version (if using raw local build): 3.8.10
 - Typescript version (if using raw local build): 4.3.5

**Comment by okunator** [comment]
Seems like you have pretty old typescript version. Try to update it with `npm install -g typescript@latest` or `npm update`

**Comment by okunator** [comment]
Have you made any changes to `tsconfig.json`?

**Comment by okunator** [comment]
And `"target": "es2022"` in `tsconfig.json`?

**Comment by okunator** [comment]
version 4.5.4

**Comment by okunator** [comment]
In `tsconfig.json`, try if switching the `es2017` in the `lib` array to `es2022` would work

**Comment by jdreo** [comment]
Apparently the `npm update` needs to be run from the `oncodash-app` sub-directory and not from the top-level one. I bumped to es2022 and did that, and now it works.

**Comment by okunator** [comment]
Great! closing this issue for now.
