### ISSUE TITLE
Write documentation's first draft.

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#5]
- [x] docstrings in main entrypoints,
- [x] main page with ToC,
- [x] backend architecture summary page,
- [x] frontend architecture summary page,
- [x] docstrings in frontend,
- [x] docstrings in backend.

**Comment by tuner** [comment]
Should we standardise on reStructuredText or Markdown? Sphinx supports both, MkDocs supports only markdown.

Both share some traits: https://gist.github.com/javiertejero/4585196

**Comment by jdreo** [comment]
Ideally, we would have a single system and a good integration of both frontend and backend, with common pages.

**Comment by jdreo** [comment]
Versio n8c2aae5a8cbd32a0e6244e0a9f19bc7a4f127ce4 submitted to review.
