### ISSUE TITLE
Atomic assignment for `item` members in the composition example

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#56]
In the example introduced by PR #53, the assignment of `this.item_id` and `this.item` should be made atomic, despite the asynchronous call to `fetch`.

As pointed out by @tuner:

> `this._item_id` and `this.item` are not set atomically. It might make sense to either:
> 1. set `this._item_id` once the fetch completes or
> 2. check that `this._item_id` and the id of the fetched item actually match and only set `this.item` if they do.

**Comment by prittt** [comment]
Does this issue still apply with the new react based code version?
