### ISSUE TITLE
Clinical timeline backend

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#60]
- [x] Add a standardized backend for fetching clinical timeline data.
- [x] Add a random data generator that can populate the clinical timeline data.

**Comment by prittt** [comment]
Done in react branch.

Backend for fetching (importing) clinical timeline data. [import_timelinerecords_and_fake_clinicaldata.py](https://github.com/oncodash/oncodash/blob/react/backend/clin_overview/management/commands/import_timelinerecords_and_fake_clinicaldata.py)
