### ISSUE TITLE
Human readable time scales

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#62]
Use a human-readable time scale for clinical timelines.
Months is preferred, but days or years may be added when zooming in/out.

**Comment by jdreo** [comment]
Use a human-readable time scale for clinical timelines.
Months is preferred, but days or years may be added when zooming in/out.

**Comment by prittt** [comment]
Done in react branch. It's quite hard to have human-readable time scales without having the real dates, so the application considers the 1st of January 2000 as the "zero" date. All the other dates are relative to this one.
