### ISSUE TITLE
Setup meaningful axis and thresholds for clinical timelines

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#65]
Axis should follow common values, thresholds should follow clinicians guidelines.

- [x] Get meaningful values from the clinician.
- [x] Scale axis.
- [x] Show units.
- [x] Configure thresholds.
- [x] Show thresholds as thin horizontal lines.

**Comment by prittt** [comment]
We agreed there is no reason to have online configurable thresholds. All the other things are solve in the react branch.
