### ISSUE TITLE
Improve clinical timelines display

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#66]
- [x] Reorder timelines in that order:
    1. CA125
    2. HB
    3. Neutrophiles (when available)
    4. Leukocytes
    5. Platelets
 - [ ] Use meaningful colors for both lines and colored sections.
 - [x] Adapt height to the importance of the data source.

**Comment by prittt** [comment]
The colors are left to Rachel and Johann. All the other things are fixed.

**Comment by prittt** [comment]
IMHO, colors are fine now.

**Comment by jdreo** [comment]
We are going to look for a polished patient card and ask Johanna about various options, we will probably discuss with her the colors during the demo.

**Comment by prittt** [comment]
Any news from this? Can we close it?
