### ISSUE TITLE
Improve patient card

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#67]
- [x] Use key/value display.
- [x] Order of main fields: age, BMI, treatment strategy, residual tumor in surgery.
- [x] Use a visual grammar for highlighting importance.
- [x] Find another visual grammar for the tertiary section:
    - [x] data are in fact ternary: Yes/No/Don’t know (not binary).
    - [x] group by categories (biological features, scans, etc.)

**Comment by prittt** [comment]
Solved in react branch with commit 3bb796e468fffa73b9f921d7161ab62c03aea33b.
