### ISSUE TITLE
NOT NULL constraint failed on clinical time series

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#77]
# Summary

When building up the docker container from scratch, migration fails on a constraint for clinical time series.

# Bug full description

Docker-compose build ends up on an integrity error during migration (see full stack below):

>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.IntegrityError: NOT NULL constraint failed: new__clin_overview_clinicaldata.time_series

# Steps to reproduce

Building with the command:

> docker-compose build --no-cache && docker-compose run --rm backend sh -c "python manage.py makemigrations" && docker-compose run --rm backend sh -c "python manage.py migrate" && docker-compose run --rm backend sh -c "python manage.py flush --no-input" && docker-compose run --rm backend sh -c "python manage.py fake_data -n 10" && docker-compose up

# Logs / Screenshots

> Operations to perform:
>   Apply all migrations: admin, auth, authtoken, clin_overview, contenttypes, core, explainer, sessions, side_effects
> Running migrations:
>   Applying clin_overview.0004_clinicaldata_event_series...Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.IntegrityError: NOT NULL constraint failed: new__clin_overview_clinicaldata.time_series
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     main()
>   File "manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 89, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 246, in handle
>     fake_initial=fake_initial,
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 126, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 106, in database_forwards
>     field,
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 330, in add_field
>     self._remake_table(model, create_field=field)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 289, in _remake_table
>     self.quote_name(model._meta.db_table),
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 145, in execute
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> django.db.utils.IntegrityError: NOT NULL constraint failed: new__clin_overview_clinicaldata.time_series
> 

# Environment

 - Oncodash Version: 4ae9bed
 - OS: Ubuntu 20.04.5 LTS

For developers:
 - Docker version: 20.10.22, build 3a2c30b
 - Docker-compose version: v2.0.1

**Comment by prittt** [comment]
Hi there. I'm from mobile so I took a very quick look at the issue. Your are running the fake population command that is no longer supported (Readme to be updated). You should instead use this command to populate the database "python manage.py import_timelinerecords_and_clinicaldata -clinicalpath <clinical filepath> -timelinepath <timeline filepath>" (you can find it in the development section of the Readme). Data files are in the decider wiki. Only utf8 csv are supported, so you need to export/covert excel files in this format before running the command.

**Comment by jdreo** [comment]
My bad, I should have thought about that, sorry for the noise.

**Comment by jdreo** [comment]
When trying with either files from 2023-01-02 or files from october 2022, on Docker or local install, using `python manage.py import_timelinerecords_and_clinicaldata -clinicalpath clinical_2022-09-26.csv -timelinepath timeline_2022-10-14.csv`:

> ...................................................................................................
> Traceback (most recent call last):
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'patient_id'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/nojhan/code/oncodash/oncodash/backend/clin_overview/management/commands/import_timelinerecords_and_clinicaldata.py", line 62, in handle
>     patient_id                                    = handle_int_field(row["patient_id"]),
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/series.py", line 942, in __getitem__
>     return self._get_value(key)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/series.py", line 1051, in _get_value
>     loc = self.index.get_loc(label)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'patient_id'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
>     return self._engine.get_loc(casted_key)
>   File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
>   File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
> KeyError: 'patient_id'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 22, in <module>
>     main()
>   File "manage.py", line 18, in main
>     execute_from_command_line(sys.argv)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
>     utility.execute()
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
>     output = self.handle(*args, **options)
>   File "/home/nojhan/code/oncodash/oncodash/backend/clin_overview/management/commands/import_timelinerecords_and_clinicaldata.py", line 115, in handle
>     print("When importing patient", row["patient_id"], "the following error occours:", e)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/series.py", line 942, in __getitem__
>     return self._get_value(key)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/series.py", line 1051, in _get_value
>     loc = self.index.get_loc(label)
>   File "/home/nojhan/code/oncodash/oncodash/backend/backendEnv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
>     raise KeyError(key) from err
> KeyError: 'patient_id'
>

**Comment by jdreo** [comment]
Data structure has changed.
