### ISSUE TITLE
Login does not trigger

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#79]
# Summary

After validating an admin login, no event happens. The login dialog is still open, and no data are loaded.

# Bug full description

The dialog fields shows transient green checkmarks.

# Steps to reproduce

1. local install
2. create admin user
3. login button
4. credential entered
5. click "submit"

# Expected behavior

The dialog should close itself and a page should be loaded.

# Environment
Oncodash Version: https://github.com/oncodash/oncodash/commit/937978011cd5c5616b0ced34947d474014095aed
    OS: core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch

For developers:

    Docker version: 20.10.22, build 3a2c30b
    Docker-compose version: v2.0.1

**Comment by prittt** [comment]
Have you created any admin user from django? Which browser are you using?

**Comment by jdreo** [comment]
I just created the superuser, as indicated in the INSTALL file. Using Firefox 108 and Chromium 108.

**Comment by prittt** [comment]
Are you using docker? In this case, the python command must be preceded by "docker-compose run --rm backend sh", but I guess you already know it.

**Comment by jdreo** [comment]
No, I'm using a local install, for now.

**Comment by prittt** [comment]
Are you sure the login credentials are correct and the user actually exists? To verify this you can connect to the local mysql db. We noticed that django backend doesn't send the same messages that nodejs does so if something is wrong in your credential/user existance it won't simply login, showing again the same page.

**Comment by prittt** [comment]
BTW, the missing-error-message issue is already solved and it will be pushed in a while.

**Comment by jdreo** [comment]
The user actually exists in the `core_user` table. Changing it to a very simple one with `python manage.py changepassword` does not help. However, now I see the error message ("Incorrect username and/or password!!!").

**Comment by jdreo** [comment]
One surprising thing is that the `name` field is marked as `NOT NULL` in the schema, but is actually made NULL by the `createsuperuser` script.

**Comment by prittt** [comment]
The createsuperuser script is part of django, we cannot/shouldn't modify it. I never had problem with it. Please note that the login of oncodash asks for the email and not the username.

**Comment by jdreo** [comment]
Filling up the name field in an existing user does not help.

Creating a test user in the Django shell does not help:
`````  
>>> import core.models
>>> user = core.models.User.objects.create_user("test","test")
>>> user
<User: test>

**Comment by jdreo** [comment]
I still have this problem after (several) fresh installs.
