### ISSUE TITLE
Document the existing data workflow

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#92]
Oncodash should have a page explaining the current data management workflow:
- [ ] how are updated the clinical data
- [ ] how are updated the sequencing data
- [ ] how are updated the cancer database data

This should be available as a page of the website, without giving sensitive details about the infrastructure of Decider, but explaining the expected workflow from a third-party user point of view.

**Comment by isoviita** [comment]
Would the suitable location for clinical data flow description be this page? https://oncodash.github.io/oncodash/backend/clinical.html
